### ISSUE TITLE
Get post content by ID on specific page

### ISSUE THREAD

**Issue by Zyles** [develodesign/vsf-wp#31]
How do you get a posts content by ID and inject that data into a specific location.

For example the sidebar on a category, category footer, in the category description or any other custom location etc.

**Comment by collymore** [comment]
Hi, you'd be best to implement a new method like loadPostBySlug  or loadPostById. 
Take a look at the loadCategoryBySlug function in the actions file 
https://github.com/develodesign/vsf-wp/blob/master/store/actions.ts
