### ISSUE TITLE
Improvement suggestion: Fix searchAdapter from breaking localized routes

### ISSUE THREAD

**Issue by dsjacobsen** [develodesign/vsf-wp#32]
Improvement suggestion

The searchAdapter is checking Request.store and setting the storeview accordingly. If multiStore is enabled Request.store should check for "undefined" value instead of null value else it will conflict with the router and set localized routes to match default storeview.

File: lib/searchAdapter.ts

Around line 15: 
```bash
const storeView = (Request.store === null) ? currentStoreView() : prepareStoreView(Request.store)
```

Change to: 

```bash
const storeView = (Request.store === undefined) ? currentStoreView() : prepareStoreView(Request.store)
```

Tested in VSF 1.9 and 1.10

**Comment by dimasch** [comment]
@dsjacobsen Thanks, Daniel.
You can check on `v0.2.0` tag?

**Comment by dsjacobsen** [comment]
@dimasch Thats great!
