### ISSUE TITLE
Feature: WooCommerce implementation 

### ISSUE THREAD

**Issue by NurdinDev** [develodesign/vsf-wp#35]
there is a plugin for GraphQL and WooCommerce from the same team, https://github.com/kidunot89/wp-graphql-woocommerce

because I'm trying to integrate Woo instead of Magento in VueSF.

I don't know if you have this already in the roadmap?

Thank you.

**Comment by collymore** [comment]
This would be an integration for the main Vue Storefront project and not this extension. This extension is only concerned with post, pages and category data
