### ISSUE TITLE
New version for VSF-2

### ISSUE THREAD

**Issue by earwickerh** [develodesign/vsf-wp#39]
@dimasch @collymore  @cnviradiya Any one working on VSF2  integration? There's a repo/thread concerning Woo and vsf2. Might prove useful to pool forces towards a common goal... https://github.com/Oxyssweden/vsf-woocommerce/discussions/2

**Comment by andreasradloff** [comment]
Hi,
I'm one of the authors of the Woo VSF2 integration. I have some work done for the WP->VSF2 integration that I will post somewhere this week.

**Comment by andreasradloff** [comment]
Here's the version for VSF2:
https://github.com/Oxyssweden/vsf-wordpress
